sudo: false
language: node_js
node_js:
  - '6'
  - '8'

install:
  - npm i npminstall && npminstall

before_script:
  - tests/travis/redis_setup.sh

script:
  - npm run ci

after_script:
  - npminstall codecov && codecov

services:
  - redis-server
