sudo: required
language: node_js
node_js:
  - '6'
  - '8'

install:
  - npm i npminstall && npminstall

script:
  - npm run ci

services:
  - redis-server

after_script:
  - npminstall codecov && codecov

before_script:
  - test/travis/redis_setup.sh